# Workflow for matrix

name: Self Hosted Matrix

on: workflow_dispatch

jobs:
    build:
        runs-on: self-hosted
        strategy:
            fail-fast: true
            matrix:
                # node-version: [14.x, 16.x]
                # os: [ubuntu-latest, windows-latest]
                browser: [chromim, firefox, webkit]
        steps:
        # - uses: actions/checkout@v2
        # - name: Install dependencies
        #   run: npm ci
        # - name: Install Playwright Browsers
        #   run: npx playwright install --with-deps
        - name: Run Playwright tests on  ${{ matrix.browser }}
          if: always()
          run: npx playwright test test.spec.js --retries=0 --config matrix.config.js --project=${{matrix.browser}}
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: smoke-report-${{matrix.browser}}
            path: playwright-report/
            retention-days: 1
