# This is a basic workflow to help you get started with Actions
name: Self-Hosted Runner
on:
    workflow_dispatch:
jobs:
    smoke_test:
        runs-on: WINDOWS10HOST
        steps:
        - name: Checkout Repository # name: Custom name for the step 
          # uses: actions/checkout@v2 # uses: Use a pre-built action
          uses: actions/checkout@v3 # uses: Use a pre-built action
        # - name: Set up Node. js # name: Custom name for the step 
        #   uses: actions/setup-node@v2 # action_name: Name of the action to use 
        #   with: # with: Input values for the action
        #     node-version: '14'
        # - name: Install Dependencies # name: Custom name for the step 
        #   run: npm install # run: Execute a shell command within the step
        # - name: Run Tests # name: Custom name for the step
        #   run: npx playwright test # command_to_execute: Shell command to be executed
        
        # - name: echo hello
        #   run: echo "Hello buddy"
        # - name: list directory
        #   run: ls
        
        # - uses: actions/setup-node@v3
        #   with:
        #     node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
        - name: Run Playwright tests
          run: npx playwright test smoke/ --config github.config.js
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 1
        
