name: Sequential Job Execution

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run some task in job1
        run: |
          echo "Running job1"
          # Simulate a failure or success
          exit 0  # Change to exit 0 for success, exit 1 to simulate failure

  job2:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' && job1.outputs.result == 'success' }}
    steps:
      - name: Check if job1 succeeded
        run: echo "Running job2"

  job3:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' && job2.outputs.result == 'success' }}
    steps:
      - name: Check if job2 succeeded
        run: |
          echo "Running job3"
          # Simulate a failure
          exit 1  # Exit with non-zero status code to simulate failure

  job4:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' && (job3.outputs.result == 'success' || job3.outputs.result == 'failure') }}
    steps:
      - name: Check if job3 succeeded or failed
        run: echo "Running job4"
