name: Sequential Job Execution

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: self-hosted
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Run some task in job1
        run: |
          echo "Running job1"
          # Simulate a failure or success
          exit 0  # Change to exit 0 for success, exit 1 to simulate failure

  job2:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' && success() }}
    steps:
      - name: Check if job1 succeeded
        if: ${{ job1.outputs.result == 'success' }}
        run: |
          echo "Running job2"
          # Additional steps for job2

  job3:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' && success() }}
    steps:
      - name: Check if job2 succeeded
        if: ${{ job2.outputs.result == 'success' }}
        run: |
          echo "Running job3"
          # Simulate a failure
          exit 1  # Exit with non-zero status code to simulate failure

  job4:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' && (success() || failure()) }}
    steps:
      - name: Check if job3 succeeded or failed
        if: ${{ job3.outputs.result == 'success' || job3.outputs.result == 'failure' }}
        run: |
          echo "Running job4"
          # Additional steps for job4
