# This is a basic workflow to help you get started with Actions
name: Smoke Tests in All Environments
on:
    workflow_dispatch:
jobs:
    qa_test:
        environment: 'QA'
        env:
            ENV_NAME: ${{ vars.ENV_NAME }}
            URL: ${{ vars.URL }}
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{secrets.PASSWORD}}
            EMAIL: ${{ secrets.EMAIL }}
        runs-on: AUTOMATION_WIN10
        steps:
        - name: Checkout Repository # name: Custom name for the step 
          uses: actions/checkout@v3 # uses: Use a pre-built action
        - name: Install dependencies
          run: npm ci
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
        - name: Run Playwright tests
          run: npx playwright test smoke/ --config github.config.js
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: qa-report
            path: playwright-report/
            retention-days: 1

    dev_test:
        environment: 'DEV'
        env:
            ENV_NAME: ${{ vars.ENV_NAME }}
            URL: ${{ vars.URL }}
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{secrets.PASSWORD}}
            EMAIL: ${{ secrets.EMAIL }}
        runs-on: AUTOMATION_WIN10
        # needs: qa_test
        steps:
        - name: Printing current dir
          run: pwd
        - name: Add delay before cleanup
          run: sleep 10
        - name: Checkout Repository # name: Custom name for the step 
          uses: actions/checkout@v3 # uses: Use a pre-built action
        - name: Install dependencies
          run: npm ci
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
        - name: Run Playwright tests
          run: npx playwright test smoke/ --config github.config.js
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: dev-report
            path: playwright-report/
            retention-days: 1
        
    prod_test: # This job requests for approval before running the job since it uses the environment 'PROD' 
        environment: 'PROD' # This environment requests approval for access before the run
        env:
            ENV_NAME: ${{ vars.ENV_NAME }}
            URL: ${{ vars.URL }}
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{secrets.PASSWORD}}
            EMAIL: ${{ secrets.EMAIL }}
        runs-on: AUTOMATION_WIN10

        steps:
        - name: Run Playwright tests
          run: npx playwright test smoke/ --config github.config.js
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: dev-report
            path: playwright-report/
            retention-days: 1
        
